#!/usr/bin/env python3
"""Builds theremingoat.js from the folder list of github.com/ThereminGoat/force-curves.

Each folder is one measured switch. Footprint and type are guessed from the name;
anything that doesn't look special is assumed to be a normal MX-style switch.
Run from the repo root:  python tools/import_theremingoat.py
"""
import json
import re
import urllib.parse
import urllib.request

REPO = "ThereminGoat/force-curves"
TREE_URL = f"https://api.github.com/repos/{REPO}/git/trees/main"

RULES = [  # first match wins
    ("other", r"\b(alps|topre|buckling|inductive|ec)\b"),
    ("he", r"\b(he|magnetic|hall effect|mag)\b"),
    ("choc2", r"\bchoc\b.*\bv2\b"),
    ("choc1", r"\bchoc\b"),
    ("lp", r"\b(low ?pro(file)?|lp|ks-33|ks-27)\b"),
    ("optical", r"\boptical\b"),
]
# Only explicit words: colors like "red" mean different things across brands.
TYPES = [("clicky", r"\b(click|clicky|clicking)\b"), ("tactile", r"\btactile\b"), ("linear", r"\blinear\b")]


def classify(name):
    low = name.lower()
    family = next((f for f, rx in RULES if re.search(rx, low)), "mx")
    kind = next((t for t, rx in TYPES if re.search(rx, low)), "unknown")
    return family, kind


def main():
    req = urllib.request.Request(TREE_URL, headers={"Accept": "application/vnd.github+json"})
    tree = json.load(urllib.request.urlopen(req))["tree"]
    out = []
    for node in tree:
        if node["type"] != "tree" or node["path"].startswith("."):
            continue
        name = node["path"]
        family, kind = classify(name)
        entry = {
            "name": name, "type": kind, "family": family, "source": "tg",
            "url": f"https://github.com/{REPO}/tree/main/{urllib.parse.quote(name)}",
        }
        if family == "mx" and name.lower().startswith("outemu"):
            entry["gauge"] = "thin"
        out.append(entry)
    with open("theremingoat.js", "w", encoding="utf-8") as f:
        f.write("// Generated by tools/import_theremingoat.py. Do not edit by hand.\n")
        f.write("const TG_SWITCHES = " + json.dumps(out, ensure_ascii=False, indent=0) + ";\n")
    print(f"wrote {len(out)} switches")


if __name__ == "__main__":
    main()
